word:
  meaning: fantastic
number:
  value: 369
sauna:
  availableSeats: 3
ballerina:
  performanceQuality1: 1
  performanceQuality2: 3
  performanceQuality3: 5
week:
  days: Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday

