server:
  port: 9002

pharmacy:
  port: http://localhost:9004/patients

beds:
  port: http://localhost:9003/patients

database:
  diseases:
    - symptoms: Spots
      condition: Chickenpox
    - symptoms: Headache
      condition: Headache
    - symptoms: Stomachache
      condition: Stomachache
    - symptoms: Rash
      condition: Ringworm
    - symptoms: Swollen neck
      condition: Rubella (German Measles)

