list:
  messages:
    - text: It is certain.
    - text: It is decidedly so.
    - text: Whithout a doubt.
    - text: Yes - definitely.
    - text: You may rely on it.
    - text: Reply hazy, try again.
    - text: Ask again later.
    - text: Better not tell you now.
    - text: Cannot predict now.
    - text: Concentrate and ask again.
    - text: Don't count on it.
    - text: My reply is no.
    - text: My sources say no.
    - text: Outlook not so good.
    - text: Very doubtful.