list:
  customer:
    - name: Ms. Sofia
    - name: Mrs. Isabela
    - name: Ms. Camila
    - name: Mrs. Valentina
    - name: Ms. Valeria
    - name: Mrs. Mariana
    - name: Mr. Santiago
    - name: Mr. Sebastian
    - name: Mr. Matias
    - name: Mr. Mateo
    - name: Mr. Alejandro
    - name: Mr. Diego
    - name: Daniela Threepwood
    - name: Ms. Gabriela Threepwood
    - name: Mrs. Martina Threepwood
    - name: Mr. Samuel Threepwood
    - name: Lucia
    - name: Sara
    - name: Emma
    - name: Augustin
    - name: Juan Pablo
    - name: Rodrigo

drafts:
    template:
      - greeting: Good day
        text: don’t forget our 20% discount on tickets this Friday!
      - greeting: Dear
        text:  you and your friends will have so much fun at the cinema this Friday with a 20% discount!
      - greeting: My dearest
        text:  your lovely family gives you a 20% discount on tickets this Friday!
      - greeting: Hello
        text: ! How about a Friday night movie? This week with a 20% discount!
