spring:
  data:
    mongodb:
      port: mongodb://localhost/todos

server:
  port: 9001

dataset:
  tweets:
    - user: Norbert
      message: I like coding!
      likes: 5
      comments: That's awesome!, Keep up the good work!, I like it too.
      timestamp: 27-03-2019
    - user: Adib
      message: I wanna go home.
      likes: 0
      comments: Finish work first!, Mee too.
      timestamp: 27-03-2019