server:
  port: 9005

spring:
  datasource:
    url: jdbc:mysql://localhost/drhouse_accountancy?useSSL=false
    username: norbert
    password: sql
  jpa:
    hibernate:
      ddl-auto: update

dataset:
  prices:
    treatment: 35.00
    medicine: 23.50
    surgery: 10000
    aspirin: 5.01
