spring:
  data:
    mongodb:
      uri: mongodb://localhost/beds

server:
  port: 9003

dataset:
  diseases:
    - condition: Headache
      treatment: Wait for the doctor to get the list of medicaments prescribed, please.
    - condition: Stomachache
      treatment: Wait for the doctor to get the list of medicaments prescribed, please.
    - condition: Chickenpox
      treatment: Wait for the doctor to get the cream prescribed, please.
